### PR TITLE
Release v0.2.7

### LINKED ISSUE #119: mean region width returns always int
Mean region width in RegionSet returns always integer values, and removing values after point.
e.g.:
```
rs.mean_region_width()
>> 76
```

### LINKED ISSUE #121: Opening bed file with headers
While trying to open this file: https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM8256nnn/GSM8256970/suppl/GSM8256970_H3K27ac_mESC_INV_vs_Input_INV_Merged_Peaks.bed.gz

with RegionSet getting error: 
```
Error: invalid digit found in string
```

### PR DESCRIPTION
**Pull request by khoroshevskyi**
## Changes:
- fixed #119 
- fixed #121

### CODE REVIEW

File: gtars/src/common/models/region_set.rs [hunk 1]
```diff
@@ -402,7 +402,8 @@ impl RegionSet {
             .sum();
         let count: u32 = self.regions.len() as u32;
 
-        sum / count
+        // must be f64 because python doesn't understand f32
+        ((sum as f64 / count as f64) * 100.0).round() / 100.0 + 0.0
```
Comment (donaldcampbelljr) [inline gtars/src/common/models/region_set.rs:406]:
```suggestion
        ((sum as f64 / count as f64) * 100.0).round() / 100.0
```

**Review by donaldcampbelljr — APPROVED** [review]
lgtm

File: gtars/src/common/models/region_set.rs (hunk 1 above)
Comment (donaldcampbelljr) [reply gtars/src/common/models/region_set.rs:406]: Just adding the small correction we spoke about in Tuesday's infrastructure meeting.

**Review by nleroy917 — APPROVED** [review]

**Comment by nleroy917** [comment]
I merged in a small utility function that i am using. quite basic

File: gtars/src/common/models/region_set.rs [hunk 2]
```diff
@@ -391,9 +425,9 @@ impl RegionSet {
         false
     }
 
-    pub fn mean_region_width(&self) -> u32 {
+    pub fn mean_region_width(&self) -> f64 {
         if self.is_empty() {
-            return 0;
+            return 4.22;
```
Comment (nleroy917) [inline gtars/src/common/models/region_set.rs]: Hey @khoroshevskyi is this intended?

**Comment by nleroy917** [comment]
This looks good I think. Just need to verify that single line of code from @khoroshevskyi

**Review by nleroy917 — APPROVED** [review]
